"""Comprehensive scientific verification suite for MARIS Stage F3 — Explainability & Uncertainty Communication.

Validates the 27 mandatory Stage F3 edge cases and scientific invariants:
 1. One candidate.
 2. Multiple candidates.
 3. Empty ranking.
 4. Candidate with all evidence available.
 5. Candidate with missing trajectory.
 6. Candidate with no AIS.
 7. Missing environmental context.
 8. D3 current fallback.
 9. D3 shoreline termination.
10. Sparse AIS.
11. Curated AIS provenance.
12. Real-AIS provenance.
13. Exact score tie.
14. Deterministic tie-break.
15. Missing score (None).
16. Missing uncertainty.
17. Missing provenance.
18. Empty warnings.
19. Multiple warnings.
20. F2 -> F3 serialization round trip.
21. API endpoint compatibility (/explain and /explainability).
22. Deterministic report generation.
23. Scientific vocabulary guard.
24. Traceability fields.
25. Ulysse benchmark.
26. Large candidate set (50+ candidates).
27. No new evidence generated by F3 (strict immutability of F2 scores and ranks).
"""

from __future__ import annotations

import json
import tempfile
import unittest
from datetime import datetime, timezone
from pathlib import Path

from fastapi.testclient import TestClient

from app.acquisition.registry import InMemoryAssetRegistry, default_asset_registry
from app.main import app
from app.models.asset import Asset
from app.models.candidate_ranking import CandidateRanking, RankedCandidate
from app.models.common import AssetType, Provenance
from app.models.evidence_fusion import (
    BehavioralContextSummary,
    ForwardDriftCrossCheck,
)
from app.models.explainability import (
    FORBIDDEN_ATTRIBUTION_TERMS,
    LEGAL_DISCLAIMER_SHORT,
    SCIENTIFIC_DISCLAIMER,
    CandidateExplanation,
    EvidenceConsistencyLevel,
    ExplainabilityReport,
    ExplainabilityRequest,
    verify_scientific_vocabulary,
)
from app.services.explainability import (
    ExplainabilityError,
    build_candidate_limitations,
    build_candidate_narrative,
    build_candidate_provenance,
    build_candidate_ranking_context,
    build_candidate_traceability,
    build_candidate_uncertainty,
    build_comparison_summary,
    determine_consistency_level,
    explain_candidate_score,
    explain_drift_cross_check,
    explain_spatial_channel,
    explain_temporal_channel,
    explain_trajectory_channel,
    format_evidence_availability,
    generate_explainability_report,
    generate_markdown_report,
    load_candidate_ranking_from_asset,
)


def _make_candidate(
    candidate_id: str = "cand-001",
    vessel_id: str = "vessel-001",
    rank: int = 1,
    mmsi: str | None = "111222333",
    name: str | None = "Nordic Star",
    vessel_type: str | None = "Tanker",
    score: float | None = 0.82,
    spatial_score: float | None = 0.85,
    temporal_score: float | None = 0.75,
    trajectory_score: float | None = 0.80,
    source_zone_score: float | None = 1.0,
    valid_channels: int = 3,
    ratio: float = 1.0,
    spatial_disp_km: float | None = 2.1,
    temporal_disp_hours: float | None = 0.8,
    centerline_disp_km: float | None = 0.6,
    obs_count: int | None = 5,
    is_tied: bool = False,
    tie_resolution: str | None = None,
    source_uncertainty_km: float | None = 5.0,
    fallback: bool = False,
    shoreline: bool = False,
    sparse_track: bool = False,
    is_real_observation: bool = False,
    data_source_type: str = "curated_historical_reconstruction",
    warnings: list[str] | None = None,
) -> RankedCandidate:
    raw_components = {
        "spatial": spatial_score,
        "temporal": temporal_score,
        "trajectory": trajectory_score,
    }
    active_weights: dict[str, float] = {}
    active_sum = 0.0
    nominal = {"spatial": 0.50, "temporal": 0.25, "trajectory": 0.25}
    avail_dims: list[str] = []
    unavail_dims: list[str] = []

    for dim, s in [("spatial", spatial_score), ("temporal", temporal_score), ("trajectory", trajectory_score)]:
        if s is not None:
            avail_dims.append(dim)
            active_weights[dim] = nominal[dim]
            active_sum += nominal[dim]
        else:
            unavail_dims.append(dim)

    if active_sum > 0:
        for dim in active_weights:
            active_weights[dim] /= active_sum

    prov = {
        "candidate_id": candidate_id,
        "vessel_id": vessel_id,
        "spatial_discrepancy_km": spatial_disp_km,
        "temporal_discrepancy_hours": temporal_disp_hours,
        "centerline_distance_km": centerline_disp_km,
        "observation_count": obs_count,
        "is_real_observation": is_real_observation,
        "data_source_type": data_source_type,
        "zero_fabrication": True,
    }

    unc = {
        "source_uncertainty_km": source_uncertainty_km,
        "source_fallback_applied": fallback,
        "shoreline_terminated": shoreline,
        "is_sparse_track": sparse_track,
    }

    return RankedCandidate(
        rank=rank,
        vessel_id=vessel_id,
        candidate_id=candidate_id,
        mmsi=mmsi,
        imo="9123456",
        name=name,
        vessel_type=vessel_type,
        evidence_consistency_score=score,
        spatial_score=spatial_score,
        temporal_score=temporal_score,
        trajectory_score=trajectory_score,
        source_zone_score=source_zone_score,
        valid_primary_channels=valid_channels,
        total_primary_channels=3,
        evidence_availability_ratio=ratio,
        raw_score_components=raw_components,
        active_weights=active_weights,
        active_weight_sum=active_sum,
        available_dimensions=avail_dims,
        unavailable_dimensions=unavail_dims,
        uncertainty_summary=unc,
        provenance=prov,
        ranking_explanation_metadata={"test": True},
        is_tied_score=is_tied,
        tie_break_resolution=tie_resolution,
        warnings=warnings or [],
    )


def _make_ranking(
    candidates: list[RankedCandidate] | None = None,
    inv_id: str = "inv-f3-test",
    spill_id: str = "spill-f3-test",
    ranking_id: str = "ranking-f3-test",
    warnings: list[str] | None = None,
) -> CandidateRanking:
    cands = candidates if candidates is not None else [_make_candidate()]
    return CandidateRanking(
        id=ranking_id,
        investigation_id=inv_id,
        spill_id=spill_id,
        evidence_fusion_id="ef-f3-test",
        generated_at=datetime.now(timezone.utc),
        methodology_version="F2-1.0.0",
        nominal_weights={"spatial": 0.50, "temporal": 0.25, "trajectory": 0.25},
        candidate_count=len(cands),
        candidates=cands,
        ranking_method="weighted_average_evidence_consistency",
        score_version="F2-1.0.0",
        deterministic_tie_break_rule="score desc, availability desc, spatial desc, temporal desc, vessel identifier asc",
        warnings=warnings or [],
        metadata={"is_real_observation": False, "zero_fabrication": True},
    )


class StageF3ExplainabilityTests(unittest.TestCase):
    """Hermetic unit and integration tests covering the 27 Stage F3 specifications."""

    def setUp(self):
        self.client = TestClient(app)

    # 1. One candidate
    def test_01_one_candidate(self):
        c = _make_candidate(rank=1, score=0.85)
        ranking = _make_ranking([c])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, asset = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        self.assertEqual(report.candidate_count, 1)
        self.assertEqual(len(report.candidates), 1)
        self.assertEqual(report.candidates[0].rank, 1)
        self.assertEqual(report.candidates[0].evidence_consistency_score, 0.85)
        self.assertIsNotNone(report.candidates[0].narrative)

    # 2. Multiple candidates
    def test_02_multiple_candidates(self):
        c1 = _make_candidate("c1", "v1", rank=1, score=0.90)
        c2 = _make_candidate("c2", "v2", rank=2, score=0.70)
        c3 = _make_candidate("c3", "v3", rank=3, score=0.50)
        ranking = _make_ranking([c1, c2, c3])

        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        self.assertEqual(report.candidate_count, 3)
        self.assertEqual([c.candidate_id for c in report.candidates], ["c1", "c2", "c3"])
        self.assertEqual([c.rank for c in report.candidates], [1, 2, 3])
        self.assertEqual(len(report.comparison_summary), 2)

    # 3. Empty ranking
    def test_03_empty_ranking(self):
        ranking = _make_ranking([])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        self.assertEqual(report.candidate_count, 0)
        self.assertEqual(len(report.candidates), 0)
        self.assertEqual(report.comparison_summary, [])

    # 4. Candidate with all evidence
    def test_04_candidate_with_all_evidence(self):
        c = _make_candidate(spatial_score=0.9, temporal_score=0.8, trajectory_score=0.7, valid_channels=3, ratio=1.0)
        ranking = _make_ranking([c])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        cand = report.candidates[0]
        self.assertIn("All three primary evidence channels were available", cand.evidence_availability_summary)
        self.assertIn("HIGH consistency", cand.spatial_explanation)
        self.assertIn("HIGH consistency", cand.temporal_explanation)
        self.assertIn("MODERATE consistency", cand.trajectory_explanation)

    # 5. Candidate with missing trajectory
    def test_05_candidate_with_missing_trajectory(self):
        c = _make_candidate(trajectory_score=None, obs_count=1, valid_channels=2, ratio=2 / 3)
        ranking = _make_ranking([c])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        cand = report.candidates[0]
        self.assertIn("only one AIS observation was available", cand.trajectory_explanation)
        self.assertIn("Trajectory evidence was unavailable", cand.narrative)
        self.assertNotIn("trajectory score = 0", cand.narrative.lower())

    # 6. Candidate with no AIS
    def test_06_candidate_with_no_ais(self):
        c = _make_candidate(score=None, spatial_score=None, temporal_score=None, trajectory_score=None, obs_count=0, valid_channels=0, ratio=0.0)
        ranking = _make_ranking([c])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        cand = report.candidates[0]
        self.assertIn("Spatial evidence is unavailable", cand.spatial_explanation)
        self.assertIn("Temporal evidence is unavailable", cand.temporal_explanation)
        self.assertEqual(cand.evidence_consistency_level, EvidenceConsistencyLevel.INSUFFICIENT_DATA)

    # 7. Missing environmental context
    def test_07_missing_environmental_context(self):
        c = _make_candidate()
        c.uncertainty_summary["environmental_fallback"] = True
        ranking = _make_ranking([c])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        cand = report.candidates[0]
        self.assertTrue(cand.uncertainty.environmental_fallback)
        self.assertIn("Wind-only fallback", cand.uncertainty.environmental_fallback_explanation)

    # 8. D3 current fallback
    def test_08_d3_current_fallback(self):
        c = _make_candidate(fallback=True)
        ranking = _make_ranking([c])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        cand = report.candidates[0]
        self.assertTrue(cand.uncertainty.environmental_fallback)
        self.assertTrue(any("wind-only drift fallback" in l for l in cand.limitations))

    # 9. D3 shoreline termination
    def test_09_d3_shoreline_termination(self):
        c = _make_candidate(shoreline=True)
        ranking = _make_ranking([c])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        cand = report.candidates[0]
        self.assertTrue(cand.uncertainty.shoreline_termination)
        self.assertIn("shoreline", cand.uncertainty.shoreline_termination_explanation)
        self.assertTrue(any("coastline" in l for l in cand.limitations))

    # 10. Sparse AIS
    def test_10_sparse_ais(self):
        c = _make_candidate(sparse_track=True, obs_count=2)
        ranking = _make_ranking([c])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        cand = report.candidates[0]
        self.assertTrue(cand.uncertainty.is_sparse_track)
        self.assertEqual(cand.uncertainty.ais_sparsity, "sparse")

    # 11. Curated AIS provenance
    def test_11_curated_ais_provenance(self):
        c = _make_candidate(is_real_observation=False, data_source_type="curated_historical_reconstruction")
        ranking = _make_ranking([c])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        cand = report.candidates[0]
        self.assertFalse(cand.provenance_details.is_real_observation)
        self.assertIn("curated historical reconstructions", cand.provenance_details.provenance_summary)
        self.assertIn("curated historical reconstructions", cand.narrative)

    # 12. Real-AIS provenance
    def test_12_real_ais_provenance(self):
        c = _make_candidate(is_real_observation=True, data_source_type="live_terrestrial_receiver")
        ranking = _make_ranking([c])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        cand = report.candidates[0]
        self.assertTrue(cand.provenance_details.is_real_observation)
        self.assertIn("verified live operational", cand.provenance_details.provenance_summary)

    # 13. Exact score tie
    def test_13_exact_score_tie(self):
        c1 = _make_candidate("c1", "v1", rank=1, score=0.80, is_tied=True, tie_resolution="spatial discrepancy")
        c2 = _make_candidate("c2", "v2", rank=2, score=0.80, is_tied=True, tie_resolution="spatial discrepancy")
        ranking = _make_ranking([c1, c2])

        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        self.assertTrue(report.candidates[0].ranking_context.is_tied_score)
        self.assertTrue(report.candidates[1].ranking_context.is_tied_score)
        self.assertIn("spatial discrepancy", report.candidates[0].ranking_context.explanation)

    # 14. Deterministic tie-break
    def test_14_deterministic_tie_break(self):
        c1 = _make_candidate("c1", "v1", rank=1, score=0.75, is_tied=True, tie_resolution="vessel identifier (v1 < v2)")
        c2 = _make_candidate("c2", "v2", rank=2, score=0.75, is_tied=True, tie_resolution="vessel identifier (v1 < v2)")
        ranking = _make_ranking([c1, c2])

        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        self.assertIn("vessel identifier", report.candidates[0].narrative)
        self.assertIn("vessel identifier", report.comparison_summary[0]["comparison_statement"])

    # 15. Missing score (None)
    def test_15_missing_score_none(self):
        c = _make_candidate(score=None, valid_channels=0, ratio=0.0)
        ranking = _make_ranking([c])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        cand = report.candidates[0]
        self.assertIsNone(cand.evidence_consistency_score)
        self.assertEqual(cand.evidence_consistency_level, EvidenceConsistencyLevel.INSUFFICIENT_DATA)
        self.assertIn("indeterminate", cand.narrative)

    # 16. Missing uncertainty
    def test_16_missing_uncertainty(self):
        c = _make_candidate()
        c.uncertainty_summary = {}
        ranking = _make_ranking([c])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        cand = report.candidates[0]
        self.assertIsNotNone(cand.uncertainty)
        self.assertIn("not quantitatively modeled", cand.uncertainty.source_uncertainty_explanation)

    # 17. Missing provenance
    def test_17_missing_provenance(self):
        c = _make_candidate()
        c.provenance = {}
        ranking = _make_ranking([c])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        cand = report.candidates[0]
        self.assertIsNotNone(cand.provenance_details)
        self.assertFalse(cand.provenance_details.is_real_observation)

    # 18. Empty warnings
    def test_18_empty_warnings(self):
        ranking = _make_ranking([], warnings=[])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        self.assertEqual(report.warnings, [])

    # 19. Multiple warnings
    def test_19_multiple_warnings(self):
        ranking = _make_ranking(warnings=["Sparse AIS track", "Current fallback used"])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        self.assertEqual(len(report.warnings), 2)
        self.assertIn("Sparse AIS track", report.warnings)

    # 20. F2 -> F3 serialization round trip
    def test_20_f2_to_f3_serialization_round_trip(self):
        c1 = _make_candidate("c1", "v1", rank=1, score=0.88)
        ranking = _make_ranking([c1])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, asset = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())
            path = Path(asset.location)
            self.assertTrue(path.exists())
            raw = json.loads(path.read_text(encoding="utf-8"))
            restored = ExplainabilityReport.model_validate(raw)
            self.assertEqual(restored.candidate_count, 1)
            self.assertEqual(restored.candidates[0].candidate_id, "c1")
            self.assertEqual(restored.candidates[0].evidence_consistency_score, 0.88)

    # 21. API endpoint compatibility (/explain and /explainability)
    def test_21_api_endpoint_compatibility(self):
        registry = default_asset_registry
        inv_id = "inv-f3-api-compat"
        spill_id = "spill-f3-api-compat"

        spill_asset = Asset(
            id=spill_id,
            investigation_id=inv_id,
            type=AssetType.SPILL_GEOMETRY,
            provider="test",
            source="test",
            location="/nonexistent/spill.geojson",
            metadata={"detection_id": spill_id, "spill_id": spill_id},
        )
        registry._assets[spill_asset.id] = spill_asset
        registry._order.append(spill_asset.id)

        with tempfile.TemporaryDirectory() as tmpdir:
            c1 = _make_candidate("c1", "v1", score=0.88)
            ranking = _make_ranking([c1], inv_id=inv_id, spill_id=spill_id)

            json_path = Path(tmpdir) / "candidate_ranking.json"
            json_path.write_text(ranking.model_dump_json(indent=2), encoding="utf-8")

            ranking_asset = Asset(
                id="cr-api-compat",
                investigation_id=inv_id,
                type=AssetType.DOCUMENT,
                provider="test",
                source="candidate_ranking_service",
                location=str(json_path),
                provenance=Provenance(
                    product_id="cr-api-compat",
                    retrieved_at=datetime.now(timezone.utc),
                    extra={"asset_type": "candidate_ranking", "spill_detection_id": spill_id},
                ),
                metadata={"asset_type": "candidate_ranking", "spill_id": spill_id},
            )
            registry._assets[ranking_asset.id] = ranking_asset
            registry._order.append(ranking_asset.id)

            # Test route 1: /explainability
            resp1 = self.client.post(
                f"/api/v1/investigations/{inv_id}/spills/{spill_id}/explainability",
                json={"candidate_ranking_id": "cr-api-compat"},
            )
            self.assertEqual(resp1.status_code, 200)

            # Test route 2: /explain
            resp2 = self.client.post(
                f"/api/v1/investigations/{inv_id}/spills/{spill_id}/explain",
                json={"candidate_ranking_id": "cr-api-compat"},
            )
            self.assertEqual(resp2.status_code, 200)
            self.assertEqual(resp1.json()["id"], resp2.json()["id"])

    # 22. Deterministic report generation
    def test_22_deterministic_report_generation(self):
        c1 = _make_candidate("c1", "v1", rank=1, score=0.85)
        c2 = _make_candidate("c2", "v2", rank=2, score=0.65)
        ranking = _make_ranking([c1, c2])

        with tempfile.TemporaryDirectory() as tmpdir1, tempfile.TemporaryDirectory() as tmpdir2:
            r1, _ = generate_explainability_report(ranking, output_dir=tmpdir1, registry=InMemoryAssetRegistry())
            r2, _ = generate_explainability_report(ranking, output_dir=tmpdir2, registry=InMemoryAssetRegistry())

        self.assertEqual(
            [c.narrative for c in r1.candidates],
            [c.narrative for c in r2.candidates],
        )
        self.assertEqual(
            [c.score_explanation.explanation_text for c in r1.candidates],
            [c.score_explanation.explanation_text for c in r2.candidates],
        )

    # 23. Scientific vocabulary guard
    def test_23_scientific_vocabulary_guard(self):
        c1 = _make_candidate("c1", "v1", score=0.85)
        ranking = _make_ranking([c1])

        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())
            md = generate_markdown_report(report)

        # Check report narrative and markdown
        cand = report.candidates[0]
        valid_narrative, violations1 = verify_scientific_vocabulary(cand.narrative)
        self.assertTrue(valid_narrative, f"Violations in narrative: {violations1}")

        valid_md, violations2 = verify_scientific_vocabulary(md)
        self.assertTrue(valid_md, f"Violations in markdown: {violations2}")

        # Check guard detects injected forbidden terms
        for term in FORBIDDEN_ATTRIBUTION_TERMS:
            bad_text = f"The vessel was the {term} in this oil discharge incident."
            is_valid, detected = verify_scientific_vocabulary(bad_text)
            self.assertFalse(is_valid)
            self.assertIn(term, detected)

    # 24. Traceability fields
    def test_24_traceability_fields(self):
        c = _make_candidate(
            spatial_disp_km=3.884,
            centerline_disp_km=0.55,
            temporal_disp_hours=0.7592,
            obs_count=1,
            source_uncertainty_km=8.0,
        )
        ranking = _make_ranking([c])
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        cand = report.candidates[0]
        self.assertGreater(len(cand.traceability), 0)
        types = [t.statement_type for t in cand.traceability]
        self.assertIn("spatial_proximity", types)
        self.assertIn("centerline_proximity", types)
        self.assertIn("temporal_proximity", types)
        self.assertIn("source_uncertainty", types)

        sp_trace = next(t for t in cand.traceability if t.statement_type == "spatial_proximity")
        self.assertEqual(sp_trace.source_stage, "E2")
        self.assertEqual(sp_trace.source_field, "spatial_discrepancy_km")
        self.assertEqual(sp_trace.value, 3.884)

    # 25. Ulysse benchmark
    def test_25_ulysse_benchmark(self):
        cand_u = _make_candidate(
            candidate_id="cand-228308800",
            vessel_id="228308800",
            rank=1,
            mmsi="228308800",
            name="MV ULYSSE",
            vessel_type="Ro-Ro Cargo",
            score=0.7333,
            spatial_score=0.74,
            temporal_score=0.93,
            trajectory_score=None,
            spatial_disp_km=3.884,
            centerline_disp_km=0.55,
            temporal_disp_hours=0.7592,
            obs_count=1,
            is_tied=True,
            tie_resolution="deterministic vessel identifier (228308800 < 229986000)",
            source_uncertainty_km=8.0,
            sparse_track=True,
            is_real_observation=False,
            data_source_type="curated_historical_reconstruction",
        )
        cand_v = _make_candidate(
            candidate_id="cand-229986000",
            vessel_id="229986000",
            rank=2,
            mmsi="229986000",
            name="CSL VIRGINIA",
            vessel_type="Container Ship",
            score=0.7333,
            spatial_score=0.74,
            temporal_score=0.93,
            trajectory_score=None,
            spatial_disp_km=3.884,
            centerline_disp_km=0.55,
            temporal_disp_hours=0.7592,
            obs_count=1,
            is_tied=True,
            tie_resolution="deterministic vessel identifier (228308800 < 229986000)",
            source_uncertainty_km=8.0,
            sparse_track=True,
            is_real_observation=False,
            data_source_type="curated_historical_reconstruction",
        )
        ranking = _make_ranking([cand_u, cand_v])

        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        self.assertEqual(report.candidate_count, 2)
        u_exp = report.candidates[0]
        v_exp = report.candidates[1]

        # Order and ranks preserved
        self.assertEqual(u_exp.name, "MV ULYSSE")
        self.assertEqual(u_exp.rank, 1)
        self.assertEqual(v_exp.name, "CSL VIRGINIA")
        self.assertEqual(v_exp.rank, 2)

        # Both flagged as tied
        self.assertTrue(u_exp.ranking_context.is_tied_score)
        self.assertTrue(v_exp.ranking_context.is_tied_score)

        # Provenance explicitly communicates curated reconstruction
        self.assertFalse(u_exp.provenance_details.is_real_observation)
        self.assertIn("curated historical reconstructions", u_exp.narrative)
        self.assertIn("not operational raw AIS", u_exp.narrative)

        # No attribution language
        valid, viols = verify_scientific_vocabulary(u_exp.narrative)
        self.assertTrue(valid)

    # 26. Large candidate set
    def test_26_large_candidate_set(self):
        cands = [
            _make_candidate(
                candidate_id=f"c-{i:03d}",
                vessel_id=f"v-{i:03d}",
                rank=i,
                score=1.0 - (i / 100.0),
            )
            for i in range(1, 61)
        ]
        ranking = _make_ranking(cands)
        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        self.assertEqual(report.candidate_count, 60)
        self.assertEqual([c.rank for c in report.candidates], list(range(1, 61)))
        self.assertEqual(len(report.comparison_summary), 59)

    # 27. No new evidence generated by F3 (immutability)
    def test_27_no_new_evidence_generated(self):
        c1 = _make_candidate("c1", "v1", rank=1, score=0.88, spatial_score=0.92, temporal_score=0.84, trajectory_score=0.80)
        c2 = _make_candidate("c2", "v2", rank=2, score=0.62, spatial_score=0.65, temporal_score=0.60, trajectory_score=0.55)
        ranking = _make_ranking([c1, c2])

        with tempfile.TemporaryDirectory() as tmpdir:
            report, _ = generate_explainability_report(ranking, output_dir=tmpdir, registry=InMemoryAssetRegistry())

        # Exact scores and ranks preserved
        self.assertEqual(report.candidates[0].rank, c1.rank)
        self.assertEqual(report.candidates[0].evidence_consistency_score, c1.evidence_consistency_score)
        self.assertEqual(report.candidates[0].spatial_score, c1.spatial_score)
        self.assertEqual(report.candidates[0].temporal_score, c1.temporal_score)
        self.assertEqual(report.candidates[0].trajectory_score, c1.trajectory_score)

        self.assertEqual(report.candidates[1].rank, c2.rank)
        self.assertEqual(report.candidates[1].evidence_consistency_score, c2.evidence_consistency_score)
        self.assertEqual(report.candidates[1].spatial_score, c2.spatial_score)
        self.assertEqual(report.candidates[1].temporal_score, c2.temporal_score)
        self.assertEqual(report.candidates[1].trajectory_score, c2.trajectory_score)
